# Generated by Django 5.1.6 on 2025-03-01 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagendaapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='workers',
            field=models.ManyToManyField(related_name='work_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
