# Generated by Django 5.1.7 on 2025-03-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagendaapp', '0004_igprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('date_publication', models.DateTimeField()),
                ('validated', models.BooleanField(default=False)),
                ('status', models.CharField(default='planified', max_length=20)),
                ('celery_task_id', models.IntegerField()),
                ('group_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_posts', to='instagendaapp.group')),
            ],
        ),
    ]
