# Generated by Django 5.1.7 on 2025-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagendaapp', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='celery_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
