# Generated by Django 5.1.7 on 2025-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagendaapp', '0006_alter_post_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='celery_task_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
