# Generated by Django 5.1.7 on 2025-04-09 19:11

import django.db.models.deletion
import instagendaapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagendaapp', '0007_alter_post_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=instagendaapp.models.upload_to)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='instagendaapp.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
