# Generated by Django 5.1.7 on 2025-04-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagendaapp", "0008_alter_post_image_url_postimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image_url",
        ),
    ]
