# Generated by Django 5.2 on 2025-04-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagendaapp', '0009_remove_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='validated',
        ),
    ]
