# Generated by Django 5.2 on 2025-04-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagendaapp', '0010_remove_post_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='unvalidated', max_length=20),
        ),
    ]
