# Generated by Django 5.2 on 2025-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagendaapp', '0011_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='igprofile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
