# Generated by Django 5.2 on 2025-04-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagendaapp', '0012_igprofile_instagram_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igprofile',
            name='instagram_username',
        ),
    ]
