name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy code
        run: |
          cd /home/django/project
          if [ -d "./Instagenda" ]; then
            cd ./Instagenda
            git pull
          else
            git clone https://github.com/HE-Arc/Instagenda.git
            cd ./Instagenda
          fi

      - name: Configure python env for django
        run: |
          cd /home/django/project/Instagenda/api
          pipenv install django
          pipenv install djangorestframework
          pipenv install gunicorn
          pipenv install psycopg2-binary
          pipenv install python-dotenv
          pipenv install django-cors-headers
          pipenv run python manage.py migrate
          pipenv run python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn

      - name: Build Vue.js
        run: |
          cd /home/django/project/Instagenda/frontend
          npm install
          npm run build