name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy code
        run: |
          cd /home/django/project
          if [ -d "./Instagenda" ]; then
            cd ./Instagenda
            git pull
          else
            git clone https://github.com/HE-Arc/Instagenda.git
            cd ./Instagenda
          fi

      - name: Configure python env for django
        run: |
          cd /home/django/project/Instagenda/api
          pipenv install
          pipenv run python manage.py migrate
          pipenv run python manage.py collectstatic --noinput
          sudo pkill -9 gunicorn
          sudo systemctl restart gunicorn

      - name: Restart Celery worker
        run: |
          sudo systemctl restart celery

      - name: Build Vue.js
        run: |
          cd /home/django/project/Instagenda/frontend
          npm install
          export NODE_OPTIONS="--max-old-space-size=1024"
          npm run build
